version: "3.8"
services:
  frontend:
    build: ./frontend
    image: dnd-character-frontend:latest
    container_name: dnd-character-frontend
    ports:
    - target: 5000
      published: 80
  backend:
    build: ./backend
    image: dnd-character-backend:latest
    container_name: dnd-character-backend
    environment:
      DATABASE_URI:
      CREATE_SCHEMA:
    ports:
    - target: 5000
      published: 5000